services:
  postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: hoops
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: auth
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    restart: always
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis_data:/data

  auth-service:
    image: ghcr.io/baracudara/hoops/auth-service:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
    ports:
      - "44044:44044"
    depends_on:
      - postgres
      - redis

volumes:
  postgres_data:
  redis_data: