env: "prod"
postgres:
  host: postgres
  port: 5432
  user: hoops
  dbname: auth
  min_conns: 2
  max_conns: 10
redis:
  host: redis
  port: 6379
  db: 0
jwt:
  access_token_ttl: 15m
  refresh_token_ttl: 720h
grpc:
  port: 44044
  timeout: 5s